sudo: true

language: java

jdk: openjdk8

# Cache maven artifacts, pip downloads and the node modules for markdownlint
cache:
  directories:
  - ~/.m2

# Do not cache the opencast artifacts to detect dependency problems
before_cache:
  - rm -rf ~/.m2/repository/org/opencastproject
  - sudo chown -R travis:travis ~/.m2 ~/.cache/pip docs/guides/node_modules/

# Default dependency installation
install:
  - sudo apt-get -qq update
  - >
     sudo apt-get install -y
     bzip2
     gzip
     procps
     tar
     unzip
     s3cmd
  - cp s3cfg ~/.s3cfg
  - sed -i "s/S3_KEY/${S3_KEY}/" ~/.s3cfg
  - sed -i "s/S3_SECRET/${S3_SECRET}/" ~/.s3cfg

script:
  - ./build.sh
