sudo: true

language: java

jdk: openjdk8

# Cache maven artifacts, pip downloads and the node modules for markdownlint
cache:
  directories:
  - ~/.m2

# Do not cache the opencast artifacts to detect dependency problems
before_cache:
  - rm -rf ~/.m2/repository/org/opencastproject
  - sudo chown -R travis:travis ~/.m2 ~/.cache/pip docs/guides/node_modules/

# Default dependency installation
install:
  - sudo apt-get -qq update
  - >
     sudo apt-get install -y
     bzip2
     gzip
     procps
     tar
     unzip
     s3cmd
  - cp s3cfg ~/.s3cfg
  - sed -i "s/S3_KEY/${S3_KEY}/" ~/.s3cfg
  - sed -i "s/S3_SECRET/${S3_SECRET}/" ~/.s3cfg

script:
  - git clone https://github.com/opencast/opencast.git
  - cd opencast
  - export branch="$(eval "${branchcmd}")"
  - export safebranch="$(echo "${branch}" | sed 's#/#_#')"
  - git checkout "${branch}"
  - export commit="$(git rev-parse --verify HEAD)"
  - echo "${commit}" | tee "${safebranch}.commit"
  - curl "https://s3.opencast.org/public/daily/${safebranch}.commit" -o prev.commit
  - cat prev.commit
  - diff -q "${safebranch}.commit" prev.commit && exit 0 || true
  - s3cmd put "${safebranch}.commit" "s3://public/daily/${safebranch}.commit"
  - sed -i 's#<module>dist-.[^l][^l].*</module>##' assemblies/pom.xml
  - >
    mvn clean install
    --batch-mode
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    -DskipTests
  - export basename="$(basename build/opencast-dist-allinone*tar.gz)"
  - s3cmd put build/opencast-dist-allinone*tar.gz "s3://public/daily/${basename}"

jobs:
  include:
    - stage: build
      env: name=develop
      before_script:
        - export branchcmd="echo develop"

    - stage: build
      env: name=stable
      before_script:
        - export branchcmd="git branch -r | sed -n 's_^.*origin/r/_r/_p' | sort -h | tail -n1"

    - stage: build
      env: name=legacy
      before_script:
        - export branchcmd="git branch -r | sed -n 's_^.*origin/r/_r/_p' | sort -h | tail -n2 | head -n1"
